//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLICAPHE.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Net;

    public partial class BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]


        public BAN(int id,string name,string status)
        {
            this.id = id;   
            this.name = name;   
            this.status = status;
        }

        public BAN(DataRow row )
        {
            this.id = (int)row["id"];
            this.name = row["name"].ToString();
            this.status = row["status"].ToString(); 
        }
        public BAN()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string status { get; set; }

        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
